# 服务名
spring:
  application:
    name: beacon-test
  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.128:8848
  # datasource
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.88.128:3306/duanxin_pingtai?characterEncoding=utf-8
    username: root
    password: 123
# 端口号
server:
  port: 20000

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true